---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: instant-search
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: Namespace
  description: Instant search project
  destinations:
  - namespace: instant-search
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/ylascombe/instant-search-demo
...
