---
# hack since there is a bug with vagrant ans ansible-local provisioner with python 3: install openshift pip dep via ansible
- name: Ensure pip is installed.
  become: true
  ansible.builtin.package:
    name: python3-pip

- name: Ensure openshift pip dependency is installed.
  ansible.builtin.pip:
    name: openshift

- name: Simulate DNS record on /etc/hosts
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: 127.0.0.1 localhost argocd.mycluster.algolia  instant-search.mycluster.algolia
    owner: root
    group: root
    mode: '0644'

...
