---

- name: Ensure argocd namespace is created.
  kubernetes.core.k8s:
    name: argocd
    api_version: v1
    kind: Namespace
    state: present

# TODO replace stable by a fixed version
# - name: Download argocd manifests.
#   ansible.builtin.get_url:
#     url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
#     dest: /tmp/argocd-deploy.yml
#     mode: 0644
- name: Use customized version of argocd.
  ansible.builtin.template:
    src: install.yaml
    dest: /tmp/argocd-deploy.yml
    mode: 0644

- name: Ensure argocd is installed.
  kubernetes.core.k8s:
    state: present
    src: /tmp/argocd-deploy.yml
    namespace: argocd

- name: Ensure argocd ingress rule is applied.
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'ingress.yml.j2') | from_yaml }}"
    namespace: argocd

- name: Ensure instant-search argocd project resource is deployed.
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'instant-search-project.yml') | from_yaml }}"
    namespace: argocd

- name: Ensure instant-search argocd app resource is deployed.
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'instant-search-app.yml') | from_yaml }}"
    namespace: argocd

- name: Wait for argocd started (here by waiting for secret generation)
  shell: kubectl get secret -n argocd
  register: test_argocd_secret
  until: "'argocd-initial-admin-secret' in test_argocd_secret.stdout"
  retries: 30
  delay: 2
  changed_when: false

- name: TMP JUST FOR DEMO retrieve argocd password
  shell: kubectl get secret -n argocd argocd-initial-admin-secret  -ojsonpath='{.data.password}' | base64 -d
  register: argocd_password
  changed_when: false

- name: TMP JUST FOR DEMO print argocd login/password
  debug:
    msg: >
      Please open ArgoCD wit URL https://argocd.mycluster.algolia/applications 
      and then use login=admin and password={{ argocd_password.stdout }} You will see instant-search app definition.
      You should also accept security warning since ArgoCD do not expose a valid SSL certificate.
...
