---

- name: Ensure argocd namespace is created.
  kubernetes.core.k8s:
    name: argocd
    api_version: v1
    kind: Namespace
    state: present

# TODO replace stable by a fixed version
# - name: Download argocd manifests.
#   ansible.builtin.get_url:
#     url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
#     dest: /tmp/argocd-deploy.yml
#     mode: 0644
- name: Use customized version of argocd.
  ansible.builtin.template:
    src: install.yaml
    dest: /tmp/argocd-deploy.yml
    mode: 0644

- name: Ensure argocd is installed.
  kubernetes.core.k8s:
    state: present
    src: /tmp/argocd-deploy.yml
    namespace: argocd

- name: Ensure argocd ingress rule is applied.
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'ingress.yml.j2') | from_yaml }}"
    namespace: argocd

# - name: Launch argocd locally
#   include_tasks: local-launch.yml
...